"""add ecritures

Revision ID: 29d10132615e
Revises: 0ab3bd68f47f
Create Date: 2026-02-09 17:24:12.194396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d10132615e'
down_revision: Union[str, Sequence[str], None] = '0ab3bd68f47f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecritures_comptables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=False),
    sa.Column('compte', sa.String(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=True),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecritures_comptables_id'), 'ecritures_comptables', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ecritures_comptables_id'), table_name='ecritures_comptables')
    op.drop_table('ecritures_comptables')
    # ### end Alembic commands ###
