"""init schema

Revision ID: 5faca5342953
Revises: 
Create Date: 2026-02-11 14:22:00.924803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5faca5342953'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fournisseur', sa.String(), nullable=True),
    sa.Column('date_facture', sa.Date(), nullable=True),
    sa.Column('numero_facture', sa.String(length=50), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('montant_ht', sa.Float(), nullable=True),
    sa.Column('montant_tva', sa.Float(), nullable=True),
    sa.Column('montant_ttc', sa.Float(), nullable=True),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('if_frs', sa.String(length=50), nullable=True),
    sa.Column('ice_frs', sa.String(length=50), nullable=True),
    sa.Column('taux_tva', sa.Float(), nullable=True),
    sa.Column('id_paie', sa.String(length=50), nullable=True),
    sa.Column('date_paie', sa.Date(), nullable=True),
    sa.Column('ded_file_path', sa.String(length=255), nullable=True),
    sa.Column('ded_pdf_path', sa.String(length=255), nullable=True),
    sa.Column('ded_xlsx_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factures_id'), 'factures', ['id'], unique=False)
    op.create_table('ecritures_comptables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=False),
    sa.Column('compte', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=True),
    sa.Column('debit', sa.Float(), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecritures_comptables_facture_id'), 'ecritures_comptables', ['facture_id'], unique=False)
    op.create_index(op.f('ix_ecritures_comptables_id'), 'ecritures_comptables', ['id'], unique=False)
    # op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('alembic_version',
    # sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    # )
    op.drop_index(op.f('ix_ecritures_comptables_id'), table_name='ecritures_comptables')
    op.drop_index(op.f('ix_ecritures_comptables_facture_id'), table_name='ecritures_comptables')
    op.drop_table('ecritures_comptables')
    op.drop_index(op.f('ix_factures_id'), table_name='factures')
    op.drop_table('factures')
    # ### end Alembic commands ###
