"""add statut facture

Revision ID: d310ff2a78fc
Revises: 29d10132615e
Create Date: 2026-02-10 10:22:22.482152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd310ff2a78fc'
down_revision: Union[str, Sequence[str], None] = '29d10132615e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ecritures_comptables', 'compte',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('factures', sa.Column('statut', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factures', 'statut')
    op.alter_column('ecritures_comptables', 'compte',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
