"""add payroll tables

Revision ID: e913ba9622fc
Revises: 1dd6991ed379
Create Date: 2026-03-03 13:32:57.499162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e913ba9622fc'
down_revision: Union[str, Sequence[str], None] = '1dd6991ed379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comptes_pcm',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('pcm_class', sa.Integer(), nullable=False),
    sa.Column('group_code', sa.String(length=10), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('is_tva_account', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tva_type', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('mappings_fournisseurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=False),
    sa.Column('supplier_ice', sa.String(length=15), nullable=False),
    sa.Column('pcm_account_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mappings_fournisseurs_cabinet_id'), 'mappings_fournisseurs', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_mappings_fournisseurs_id'), 'mappings_fournisseurs', ['id'], unique=False)
    op.create_index(op.f('ix_mappings_fournisseurs_supplier_ice'), 'mappings_fournisseurs', ['supplier_ice'], unique=False)
    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_logs_cabinet_id'), 'action_logs', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_action_logs_id'), 'action_logs', ['id'], unique=False)
    op.create_table('agents_societes',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('societe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['societe_id'], ['societes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'societe_id')
    )
    op.create_table('employes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('societe_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('cin', sa.String(length=20), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('poste', sa.String(length=200), nullable=True),
    sa.Column('date_embauche', sa.Date(), nullable=False),
    sa.Column('type_contrat', sa.String(length=20), server_default='CDI', nullable=True),
    sa.Column('salaire_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('nb_enfants', sa.Integer(), nullable=False),
    sa.Column('anciennete_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('numero_cnss', sa.String(length=30), nullable=True),
    sa.Column('affiliee_cnss', sa.Boolean(), nullable=True),
    sa.Column('statut', sa.String(length=20), server_default='ACTIF', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['societe_id'], ['societes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employes_id'), 'employes', ['id'], unique=False)
    op.create_index(op.f('ix_employes_societe_id'), 'employes', ['societe_id'], unique=False)
    op.create_table('ecritures_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=False),
    sa.Column('journal_code', sa.String(length=10), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('validated_by', sa.String(length=255), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('total_debit', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('total_credit', sa.Numeric(precision=15, scale=2), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecritures_journal_facture_id'), 'ecritures_journal', ['facture_id'], unique=False)
    op.create_index(op.f('ix_ecritures_journal_id'), 'ecritures_journal', ['id'], unique=False)
    op.create_table('immobilisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('societe_id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=True),
    sa.Column('designation', sa.String(length=500), nullable=False),
    sa.Column('categorie', sa.String(length=30), server_default='CORPORELLE', nullable=True),
    sa.Column('date_acquisition', sa.Date(), nullable=False),
    sa.Column('valeur_acquisition', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tva_acquisition', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('duree_amortissement', sa.Integer(), nullable=False),
    sa.Column('taux_amortissement', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('methode', sa.String(length=20), server_default='LINEAIRE', nullable=False),
    sa.Column('compte_actif_pcm', sa.String(length=10), nullable=True),
    sa.Column('compte_amort_pcm', sa.String(length=10), nullable=True),
    sa.Column('compte_dotation_pcm', sa.String(length=10), nullable=True),
    sa.Column('statut', sa.String(length=20), server_default='ACTIF', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ),
    sa.ForeignKeyConstraint(['societe_id'], ['societes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_immobilisations_facture_id'), 'immobilisations', ['facture_id'], unique=False)
    op.create_index(op.f('ix_immobilisations_id'), 'immobilisations', ['id'], unique=False)
    op.create_index(op.f('ix_immobilisations_societe_id'), 'immobilisations', ['societe_id'], unique=False)
    op.create_table('lignes_factures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('unit_price_ht', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('line_amount_ht', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tva_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tva_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('line_amount_ttc', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pcm_class', sa.Integer(), nullable=True),
    sa.Column('pcm_account_code', sa.String(length=10), nullable=True),
    sa.Column('pcm_account_label', sa.String(length=255), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('is_corrected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('corrected_account_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lignes_factures_facture_id'), 'lignes_factures', ['facture_id'], unique=False)
    op.create_index(op.f('ix_lignes_factures_id'), 'lignes_factures', ['id'], unique=False)
    op.create_table('bulletins_paie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('salaire_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('prime_anciennete', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('autres_gains', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salaire_brut', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cnss_salarie', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amo_salarie', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ir_retenu', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_retenues', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cnss_patronal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amo_patronal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_patronal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('salaire_net', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('coût_total_employeur', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=20), server_default='BROUILLON', nullable=False),
    sa.Column('valide_par', sa.String(length=100), nullable=True),
    sa.Column('valide_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['ecritures_journal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulletins_paie_employe_id'), 'bulletins_paie', ['employe_id'], unique=False)
    op.create_index(op.f('ix_bulletins_paie_id'), 'bulletins_paie', ['id'], unique=False)
    op.create_table('lignes_amortissement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('immobilisation_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('dotation_annuelle', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amortissement_cumule', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valeur_nette_comptable', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ecriture_generee', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['immobilisation_id'], ['immobilisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lignes_amortissement_id'), 'lignes_amortissement', ['id'], unique=False)
    op.create_index(op.f('ix_lignes_amortissement_immobilisation_id'), 'lignes_amortissement', ['immobilisation_id'], unique=False)
    op.create_table('lignes_ecritures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecriture_journal_id', sa.Integer(), nullable=False),
    sa.Column('line_order', sa.Integer(), nullable=True),
    sa.Column('account_code', sa.String(length=10), nullable=False),
    sa.Column('account_label', sa.String(length=255), nullable=True),
    sa.Column('debit', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('credit', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('tiers_name', sa.String(length=255), nullable=True),
    sa.Column('tiers_ice', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ecriture_journal_id'], ['ecritures_journal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lignes_ecritures_ecriture_journal_id'), 'lignes_ecritures', ['ecriture_journal_id'], unique=False)
    op.create_index(op.f('ix_lignes_ecritures_id'), 'lignes_ecritures', ['id'], unique=False)
    op.create_table('lignes_paie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulletin_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=300), nullable=False),
    sa.Column('type_ligne', sa.String(length=10), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('taux', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('base_calcul', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bulletins_paie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lignes_paie_bulletin_id'), 'lignes_paie', ['bulletin_id'], unique=False)
    op.create_index(op.f('ix_lignes_paie_id'), 'lignes_paie', ['id'], unique=False)
    op.drop_index(op.f('ix_journal_entries_facture_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_ecritures_lignes_ecriture_id'), table_name='ecritures_lignes')
    op.drop_index(op.f('ix_ecritures_lignes_id'), table_name='ecritures_lignes')
    op.drop_table('ecritures_lignes')
    op.drop_table('agent_societes')
    op.drop_index(op.f('ix_supplier_mappings_cabinet_id'), table_name='supplier_mappings')
    op.drop_index(op.f('ix_supplier_mappings_id'), table_name='supplier_mappings')
    op.drop_index(op.f('ix_supplier_mappings_supplier_ice'), table_name='supplier_mappings')
    op.drop_table('supplier_mappings')
    op.drop_index(op.f('ix_ecritures_comptables_date_operation'), table_name='ecritures_comptables')
    op.drop_index(op.f('ix_ecritures_comptables_facture_id'), table_name='ecritures_comptables')
    op.drop_index(op.f('ix_ecritures_comptables_id'), table_name='ecritures_comptables')
    op.drop_index(op.f('ix_ecritures_comptables_journal'), table_name='ecritures_comptables')
    op.drop_index(op.f('ix_ecritures_comptables_numero_piece'), table_name='ecritures_comptables')
    op.drop_index(op.f('ix_ecritures_comptables_societe_id'), table_name='ecritures_comptables')
    op.drop_table('ecritures_comptables')
    op.drop_index(op.f('ix_invoice_lines_facture_id'), table_name='invoice_lines')
    op.drop_index(op.f('ix_invoice_lines_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_table('pcm_accounts')
    op.drop_index(op.f('ix_entry_lines_id'), table_name='entry_lines')
    op.drop_index(op.f('ix_entry_lines_journal_entry_id'), table_name='entry_lines')
    op.drop_table('entry_lines')
    op.add_column('agents', sa.Column('is_super_admin', sa.Boolean(), nullable=True))
    op.drop_column('factures', 'ded_xlsx_path')
    op.drop_column('factures', 'ded_pdf_path')
    op.drop_column('factures', 'ded_file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factures', sa.Column('ded_file_path', sa.VARCHAR(length=255), nullable=True))
    op.add_column('factures', sa.Column('ded_pdf_path', sa.VARCHAR(length=255), nullable=True))
    op.add_column('factures', sa.Column('ded_xlsx_path', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('agents', 'is_super_admin')
    op.create_table('entry_lines',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('journal_entry_id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_line_id', sa.INTEGER(), nullable=True),
    sa.Column('line_order', sa.INTEGER(), nullable=True),
    sa.Column('account_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('account_label', sa.VARCHAR(length=255), nullable=True),
    sa.Column('debit', sa.NUMERIC(precision=15, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('credit', sa.NUMERIC(precision=15, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('tiers_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tiers_ice', sa.VARCHAR(length=15), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['invoice_lines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_lines_journal_entry_id'), 'entry_lines', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_entry_lines_id'), 'entry_lines', ['id'], unique=False)
    op.create_table('pcm_accounts',
    sa.Column('code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), nullable=False),
    sa.Column('pcm_class', sa.INTEGER(), nullable=False),
    sa.Column('group_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('account_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_tva_account', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False),
    sa.Column('tva_type', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('invoice_lines',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('facture_id', sa.INTEGER(), nullable=False),
    sa.Column('line_number', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('quantity', sa.NUMERIC(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=50), nullable=True),
    sa.Column('unit_price_ht', sa.NUMERIC(precision=15, scale=4), nullable=True),
    sa.Column('line_amount_ht', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('tva_rate', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('tva_amount', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('line_amount_ttc', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('pcm_class', sa.INTEGER(), nullable=True),
    sa.Column('pcm_account_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('pcm_account_label', sa.VARCHAR(length=255), nullable=True),
    sa.Column('classification_confidence', sa.FLOAT(), nullable=True),
    sa.Column('classification_reason', sa.TEXT(), nullable=True),
    sa.Column('is_corrected', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False),
    sa.Column('corrected_account_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_id'), 'invoice_lines', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_lines_facture_id'), 'invoice_lines', ['facture_id'], unique=False)
    op.create_table('ecritures_comptables',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('societe_id', sa.INTEGER(), nullable=False),
    sa.Column('facture_id', sa.INTEGER(), nullable=False),
    sa.Column('operation', sa.VARCHAR(length=50), nullable=False),
    sa.Column('numero_piece', sa.VARCHAR(length=50), nullable=False),
    sa.Column('date_operation', sa.DATE(), nullable=False),
    sa.Column('tiers_nom', sa.VARCHAR(length=255), nullable=True),
    sa.Column('journal', sa.VARCHAR(length=10), server_default=sa.text("'OD'"), nullable=False),
    sa.Column('statut', sa.VARCHAR(length=50), server_default=sa.text("'brouillon'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('validated_at', sa.DATETIME(), nullable=True),
    sa.Column('libelle', sa.VARCHAR(length=255), nullable=True),
    sa.Column('total_debit', sa.FLOAT(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('total_credit', sa.FLOAT(), server_default=sa.text("'0'"), nullable=False),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['societe_id'], ['societes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecritures_comptables_societe_id'), 'ecritures_comptables', ['societe_id'], unique=False)
    op.create_index(op.f('ix_ecritures_comptables_numero_piece'), 'ecritures_comptables', ['numero_piece'], unique=False)
    op.create_index(op.f('ix_ecritures_comptables_journal'), 'ecritures_comptables', ['journal'], unique=False)
    op.create_index(op.f('ix_ecritures_comptables_id'), 'ecritures_comptables', ['id'], unique=False)
    op.create_index(op.f('ix_ecritures_comptables_facture_id'), 'ecritures_comptables', ['facture_id'], unique=False)
    op.create_index(op.f('ix_ecritures_comptables_date_operation'), 'ecritures_comptables', ['date_operation'], unique=False)
    op.create_table('supplier_mappings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cabinet_id', sa.INTEGER(), nullable=False),
    sa.Column('supplier_ice', sa.VARCHAR(length=15), nullable=False),
    sa.Column('pcm_account_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_mappings_supplier_ice'), 'supplier_mappings', ['supplier_ice'], unique=False)
    op.create_index(op.f('ix_supplier_mappings_id'), 'supplier_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_mappings_cabinet_id'), 'supplier_mappings', ['cabinet_id'], unique=False)
    op.create_table('agent_societes',
    sa.Column('agent_id', sa.INTEGER(), nullable=False),
    sa.Column('societe_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['societe_id'], ['societes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'societe_id')
    )
    op.create_table('ecritures_lignes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ecriture_id', sa.INTEGER(), nullable=False),
    sa.Column('compte', sa.VARCHAR(length=20), nullable=False),
    sa.Column('libelle', sa.VARCHAR(length=255), nullable=True),
    sa.Column('debit', sa.FLOAT(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('credit', sa.FLOAT(), server_default=sa.text("'0'"), nullable=False),
    sa.ForeignKeyConstraint(['ecriture_id'], ['ecritures_comptables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecritures_lignes_id'), 'ecritures_lignes', ['id'], unique=False)
    op.create_index(op.f('ix_ecritures_lignes_ecriture_id'), 'ecritures_lignes', ['ecriture_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('facture_id', sa.INTEGER(), nullable=False),
    sa.Column('journal_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('entry_date', sa.DATE(), nullable=True),
    sa.Column('reference', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_validated', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False),
    sa.Column('validated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('validated_at', sa.DATETIME(), nullable=True),
    sa.Column('total_debit', sa.NUMERIC(precision=15, scale=2), server_default=sa.text("'0'"), nullable=True),
    sa.Column('total_credit', sa.NUMERIC(precision=15, scale=2), server_default=sa.text("'0'"), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_journal_entries_facture_id'), 'journal_entries', ['facture_id'], unique=False)
    op.drop_index(op.f('ix_lignes_paie_id'), table_name='lignes_paie')
    op.drop_index(op.f('ix_lignes_paie_bulletin_id'), table_name='lignes_paie')
    op.drop_table('lignes_paie')
    op.drop_index(op.f('ix_lignes_ecritures_id'), table_name='lignes_ecritures')
    op.drop_index(op.f('ix_lignes_ecritures_ecriture_journal_id'), table_name='lignes_ecritures')
    op.drop_table('lignes_ecritures')
    op.drop_index(op.f('ix_lignes_amortissement_immobilisation_id'), table_name='lignes_amortissement')
    op.drop_index(op.f('ix_lignes_amortissement_id'), table_name='lignes_amortissement')
    op.drop_table('lignes_amortissement')
    op.drop_index(op.f('ix_bulletins_paie_id'), table_name='bulletins_paie')
    op.drop_index(op.f('ix_bulletins_paie_employe_id'), table_name='bulletins_paie')
    op.drop_table('bulletins_paie')
    op.drop_index(op.f('ix_lignes_factures_id'), table_name='lignes_factures')
    op.drop_index(op.f('ix_lignes_factures_facture_id'), table_name='lignes_factures')
    op.drop_table('lignes_factures')
    op.drop_index(op.f('ix_immobilisations_societe_id'), table_name='immobilisations')
    op.drop_index(op.f('ix_immobilisations_id'), table_name='immobilisations')
    op.drop_index(op.f('ix_immobilisations_facture_id'), table_name='immobilisations')
    op.drop_table('immobilisations')
    op.drop_index(op.f('ix_ecritures_journal_id'), table_name='ecritures_journal')
    op.drop_index(op.f('ix_ecritures_journal_facture_id'), table_name='ecritures_journal')
    op.drop_table('ecritures_journal')
    op.drop_index(op.f('ix_employes_societe_id'), table_name='employes')
    op.drop_index(op.f('ix_employes_id'), table_name='employes')
    op.drop_table('employes')
    op.drop_table('agents_societes')
    op.drop_index(op.f('ix_action_logs_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_cabinet_id'), table_name='action_logs')
    op.drop_table('action_logs')
    op.drop_index(op.f('ix_mappings_fournisseurs_supplier_ice'), table_name='mappings_fournisseurs')
    op.drop_index(op.f('ix_mappings_fournisseurs_id'), table_name='mappings_fournisseurs')
    op.drop_index(op.f('ix_mappings_fournisseurs_cabinet_id'), table_name='mappings_fournisseurs')
    op.drop_table('mappings_fournisseurs')
    op.drop_table('comptes_pcm')
    # ### end Alembic commands ###
